version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai-bootcamp-postgres
    environment:
      POSTGRES_DB: ai_bootcamp_showcase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: